/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.me.telas;

import br.com.me.DAO.ArbitroDao;
import br.com.me.DAO.AtletaDao;
import br.com.me.DAO.CampeonatoDao;
import br.com.me.entidade.Atleta;
import br.com.me.entidade.Campeonato;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author eduardo.barbosa
 */
public class CadastroLutador extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroLutador
     */
    public CadastroLutador() {
        initComponents();
        pesquisandoCampeonato();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        lblTitulo = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        lblNacionalidade = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        varNome = new javax.swing.JTextField();
        varEstado = new javax.swing.JTextField();
        varNacionalidade = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        varAltura = new javax.swing.JFormattedTextField();
        varPeso = new javax.swing.JFormattedTextField();
        varDtNascimento = new javax.swing.JFormattedTextField();
        varCategoria = new javax.swing.JComboBox<>();
        lblAltura1 = new javax.swing.JLabel();
        lblAltura2 = new javax.swing.JLabel();
        varCPF = new javax.swing.JFormattedTextField();
        varCelular = new javax.swing.JFormattedTextField();
        lblEstado1 = new javax.swing.JLabel();
        varCampeonato = new javax.swing.JComboBox();
        btAdicionarUsuario = new javax.swing.JButton();
        btAlterarUsuario = new javax.swing.JButton();
        btExcluirUsuario = new javax.swing.JButton();
        varID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        varPesquisar = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Inscrição de Atletas");
        setToolTipText("");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 102, 102));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText(" Inscrição de Atletas");
        kGradientPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 7, -1, 30));

        lblID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("ID:");
        kGradientPanel1.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        lblNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome:");
        kGradientPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        lblIdade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIdade.setForeground(new java.awt.Color(255, 255, 255));
        lblIdade.setText("Data Nasc:");
        kGradientPanel1.add(lblIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        lblPeso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPeso.setForeground(new java.awt.Color(255, 255, 255));
        lblPeso.setText("Peso(kg):");
        kGradientPanel1.add(lblPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        lblAltura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAltura.setForeground(new java.awt.Color(255, 255, 255));
        lblAltura.setText("Altura:");
        kGradientPanel1.add(lblAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 55, -1));

        lblNacionalidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNacionalidade.setForeground(new java.awt.Color(255, 255, 255));
        lblNacionalidade.setText("País");
        kGradientPanel1.add(lblNacionalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        lblEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(255, 255, 255));
        lblEstado.setText("Estado:");
        kGradientPanel1.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        lblCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria.setText("Categoria:");
        kGradientPanel1.add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));
        kGradientPanel1.add(varNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 223, -1));
        kGradientPanel1.add(varEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 223, -1));
        kGradientPanel1.add(varNacionalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 223, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/me/icones/icone pesquisar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 116, 34, 34));
        kGradientPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 506, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\marcelo jr\\Desktop\\icones\\podium.png")); // NOI18N
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 55, -1, -1));

        try {
            varAltura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        kGradientPanel1.add(varAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 223, -1));

        varPeso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        kGradientPanel1.add(varPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 223, -1));

        try {
            varDtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        kGradientPanel1.add(varDtNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 223, -1));

        varCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Peso Leve", "Peso Médio", "Peso Pesado" }));
        kGradientPanel1.add(varCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 223, -1));

        lblAltura1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAltura1.setForeground(new java.awt.Color(255, 255, 255));
        lblAltura1.setText("CPF:");
        kGradientPanel1.add(lblAltura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 41, -1));

        lblAltura2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAltura2.setForeground(new java.awt.Color(255, 255, 255));
        lblAltura2.setText("Celular:");
        kGradientPanel1.add(lblAltura2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 74, 12));

        try {
            varCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        kGradientPanel1.add(varCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 223, -1));

        try {
            varCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        kGradientPanel1.add(varCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 223, -1));

        lblEstado1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstado1.setForeground(new java.awt.Color(255, 255, 255));
        lblEstado1.setText("Campeonato:");
        kGradientPanel1.add(lblEstado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        varCampeonato.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        kGradientPanel1.add(varCampeonato, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 223, -1));

        btAdicionarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/me/icones/icone add usuario.png"))); // NOI18N
        btAdicionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarUsuarioActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btAdicionarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        btAlterarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/me/icones/icone editar usuario.png"))); // NOI18N
        btAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarUsuarioActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btAlterarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, -1, -1));

        btExcluirUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/me/icones/icone deletar usuario.png"))); // NOI18N
        kGradientPanel1.add(btExcluirUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, -1, -1));

        varID.setEnabled(false);
        kGradientPanel1.add(varID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 72, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CPF:");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 133, -1, -1));
        kGradientPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 506, 10));

        try {
            varPesquisar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        kGradientPanel1.add(varPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 170, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        setBounds(0, 0, 510, 630);
    }// </editor-fold>//GEN-END:initComponents
    Vector<Integer> idcampeonato = new Vector<Integer>();

    public void pesquisandoCampeonato() {
        CampeonatoDao campeonatoDao = new CampeonatoDao();
        Campeonato campeonato = new Campeonato();

        ResultSet campeonatopesq = campeonatoDao.pesquisarCampeonato();
        try {
            while (campeonatopesq.next()) {
                campeonato = new Campeonato();
                idcampeonato.addElement(campeonatopesq.getInt("idcampeonato"));
                varCampeonato.addItem(campeonatopesq.getString("nome"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "erro ao pesquisar Campeonato" + ex);
        }

    }
    private void btAdicionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarUsuarioActionPerformed
        if (!validandoatleta()) {
            Atleta atleta = new Atleta();

            atleta.setNome(varNome.getText().trim());
            atleta.setNascimento(varDtNascimento.getText().trim());
            String altura = varAltura.getText().trim();
            String alturamodificada = altura.replace(",", ".");
            atleta.setAltura(Double.parseDouble(alturamodificada));
            String peso = varPeso.getText().trim();
            String pesomodificado = peso.replace(",", ".");
            atleta.setPeso(Double.parseDouble(pesomodificado));
            atleta.setCategoria(varCategoria.getSelectedItem().toString());
            atleta.setNacionalidade(varNacionalidade.getText().trim());
            atleta.setEstado(varEstado.getText().trim());
            atleta.setCpf(varCPF.getText().trim());
            atleta.setTelefone(varCelular.getText().trim());
            atleta.setCampeonato(idcampeonato.get(varCampeonato.getSelectedIndex()));
            AtletaDao atletaDao = new AtletaDao();
            boolean salvandoatleta = false;
            try {
                salvandoatleta = atletaDao.adicionarAtleta(atleta);
            } catch (SQLException ex) {
                Logger.getLogger(CadastroLutador.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (salvandoatleta == true) {
                limparcampos();
            }
        }
    }//GEN-LAST:event_btAdicionarUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AtletaDao atletaDao = new AtletaDao();

        String cpf = varPesquisar.getText().trim();
        Atleta atletapesquisado = atletaDao.pesquisarCPF(cpf);
        if (atletapesquisado == null) {
            JOptionPane.showMessageDialog(null, "CPF não encontrado");
        }
        varID.setText(atletapesquisado.getId().toString());
        varNome.setText(atletapesquisado.getNome());
        varDtNascimento.setText(atletapesquisado.getNascimento());
        String altura = atletapesquisado.getAltura().toString();
        String alturaalterada = altura.replace(".", ",");
        varAltura.setText(alturaalterada);
        varCategoria.setSelectedItem(atletapesquisado.getCategoria());
        varCelular.setText(atletapesquisado.getTelefone());
        varEstado.setText(atletapesquisado.getEstado());
        varNacionalidade.setText(atletapesquisado.getNacionalidade());
        String peso = atletapesquisado.getPeso().toString();
        String pesoalterado = peso.replace(".", ",");
        varPeso.setText(pesoalterado);
        varCPF.setText(atletapesquisado.getCpf());
        varCampeonato.setSelectedItem(atletapesquisado.getCampeonato());
        btAdicionarUsuario.setEnabled(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarUsuarioActionPerformed
        if (!validandoatleta()) {
            Atleta atleta = new Atleta();
            atleta.setId(Integer.parseInt(varID.getText()));
            atleta.setNome(varNome.getText().trim());
            atleta.setNascimento(varDtNascimento.getText().trim());
            String altura = varAltura.getText().trim();
            String alturamodificada = altura.replace(",", ".");
            atleta.setAltura(Double.parseDouble(alturamodificada));
            String peso = varPeso.getText().trim();
            String pesomodificado = peso.replace(",", ".");
            atleta.setPeso(Double.parseDouble(pesomodificado));
            atleta.setCategoria(varCategoria.getSelectedItem().toString());
            atleta.setNacionalidade(varNacionalidade.getText().trim());
            atleta.setEstado(varEstado.getText().trim());
            atleta.setCpf(varCPF.getText().trim());
            atleta.setTelefone(varCelular.getText().trim());
            AtletaDao atletaDao = new AtletaDao();
            boolean salvandoatleta = atletaDao.alterarAtleta(atleta);
            if (salvandoatleta == true) {
                limparcampos();
                btAdicionarUsuario.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btAlterarUsuarioActionPerformed

    public void limparcampos() {
        varAltura.setText("");
        varCategoria.setSelectedItem(" ");
        varDtNascimento.setText("");
        varEstado.setText("");
        varID.setText("");
        varNacionalidade.setText("");
        varNome.setText("");
        varPeso.setText("");
        varPesquisar.setText("");
        varCPF.setText("");
        varCelular.setText("");
        varCampeonato.setSelectedItem(" ");
    }

    public boolean validandoatleta() {
        if (validarnome()) {
            JOptionPane.showMessageDialog(null, "Digite um nome valido!");
            return true;
        }
        if (validandodata()) {
            JOptionPane.showMessageDialog(null, "Digite uma data de nascimento valida!");
            return true;
        }
        if (validandocpf()) {
            JOptionPane.showMessageDialog(null, "Digite um CPF valido!");
            return true;
        }
        if (validandoaltura()) {
            JOptionPane.showMessageDialog(null, "Digite uma altura valida!");
            return true;
        }
        if (validandoCampoVazio(varPeso.getText().trim())) {
            JOptionPane.showMessageDialog(null, "Digite um peso valido!");
            return true;
        }
        if (validandoCategoria()) {
            JOptionPane.showMessageDialog(null, "Selecione uma categoria valida!");
            return true;
        }
        if (valiandoCampoMenorQue3vazio(varNacionalidade.getText().trim())) {
            JOptionPane.showMessageDialog(null, "Digite um país valido!");
            return true;
        }
        if (valiandoCampoMenorQue3vazio(varEstado.getText().trim())) {
            JOptionPane.showMessageDialog(null, "Digite um estado valido!");
            return true;
        }
        return false;
    }

    public boolean validandoaltura() {
        String altura = varAltura.getText().trim();
        if (altura.equals(",")) {
            return true;
        }
        return false;
    }

    public boolean validandocelular() {
        String telefone = varCelular.getText().trim();
        int ultimoIndiceTelefone = telefone.length() - 1;
        char ultimoValor = telefone.charAt(ultimoIndiceTelefone);
        if (ultimoValor == '-') {
            return true;
        }
        return false;
    }

    public boolean validandocpf() {
        String cpf = varCPF.getText().trim();
        String primeiroCaracter = cpf.substring(0, 1);
        return primeiroCaracter.equals(".");
    }

    public boolean validandodata() {
        String data = varDtNascimento.getText().trim();
        if (data.equals("/  /")) {
            return true;
        }
        return false;
    }

    public boolean valiandoCampoMenorQue3vazio(String menorQue3) {
        if (menorQue3.length() < 3 || menorQue3.equals("")) {
            return true;
        }
        return false;
    }

    public boolean validandoCategoria() {
        String categoria = varCategoria.getSelectedItem().toString();
        if (categoria.equals(" ")) {
            return true;
        }
        return false;
    }

    public boolean validandoCampoVazio(String cv) {
        if (cv.equals("")) {
            return true;
        }
        return false;
    }

    public boolean validarnome() {
        String nome = varNome.getText().trim();
        if (nome.equals("") || nome.length() < 3) {
            return true;
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionarUsuario;
    private javax.swing.JButton btAlterarUsuario;
    private javax.swing.JButton btExcluirUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblAltura1;
    private javax.swing.JLabel lblAltura2;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstado1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNacionalidade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JFormattedTextField varAltura;
    private javax.swing.JFormattedTextField varCPF;
    private javax.swing.JComboBox varCampeonato;
    private javax.swing.JComboBox<String> varCategoria;
    private javax.swing.JFormattedTextField varCelular;
    private javax.swing.JFormattedTextField varDtNascimento;
    private javax.swing.JTextField varEstado;
    private javax.swing.JTextField varID;
    private javax.swing.JTextField varNacionalidade;
    private javax.swing.JTextField varNome;
    private javax.swing.JFormattedTextField varPeso;
    private javax.swing.JFormattedTextField varPesquisar;
    // End of variables declaration//GEN-END:variables
}
