/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.me.telas;

import br.com.me.DAO.ArbitroDao;
import br.com.me.DAO.AtletaDao;
import br.com.me.DAO.LutaDao;
import br.com.me.entidade.Atleta;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author marcelo jr
 */
public class Lutas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Lutas
     */
    public Lutas() {
        initComponents();

    }

    public void setarcampos() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        Titulo = new javax.swing.JLabel();
        LOGO = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        varIDpesquisa = new javax.swing.JTextField();
        btPesquisa = new javax.swing.JButton();
        tblCamp = new javax.swing.JTabbedPane();
        abaCampAtletas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAtletas = new javax.swing.JTable();
        btSortear = new javax.swing.JButton();
        abaCampArbitros = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblArbitros = new javax.swing.JTable();
        btArbitros = new javax.swing.JButton();
        abaCampLutas = new javax.swing.JPanel();
        luta1 = new javax.swing.JLabel();
        luta2 = new javax.swing.JLabel();
        luta3 = new javax.swing.JLabel();
        luta4 = new javax.swing.JLabel();
        luta5 = new javax.swing.JLabel();
        luta6 = new javax.swing.JLabel();
        luta7 = new javax.swing.JLabel();
        luta8 = new javax.swing.JLabel();
        var1Luta1 = new javax.swing.JTextField();
        var2Luta1 = new javax.swing.JTextField();
        var1Luta2 = new javax.swing.JTextField();
        var2Luta2 = new javax.swing.JTextField();
        var1Luta3 = new javax.swing.JTextField();
        var2Luta3 = new javax.swing.JTextField();
        var1Luta4 = new javax.swing.JTextField();
        var2Luta4 = new javax.swing.JTextField();
        var1Luta5 = new javax.swing.JTextField();
        var2Luta5 = new javax.swing.JTextField();
        var1Luta6 = new javax.swing.JTextField();
        var2Luta6 = new javax.swing.JTextField();
        var1Luta7 = new javax.swing.JTextField();
        var2Luta7 = new javax.swing.JTextField();
        var1Luta8 = new javax.swing.JTextField();
        var2Luta8 = new javax.swing.JTextField();
        vesus1 = new javax.swing.JLabel();
        vesus2 = new javax.swing.JLabel();
        vesus3 = new javax.swing.JLabel();
        vesus4 = new javax.swing.JLabel();
        vesus5 = new javax.swing.JLabel();
        vesus6 = new javax.swing.JLabel();
        vesus7 = new javax.swing.JLabel();
        vesus8 = new javax.swing.JLabel();
        Arbitro = new javax.swing.JLabel();
        varDtLuta1 = new javax.swing.JTextField();
        varDtLuta2 = new javax.swing.JTextField();
        varDtLuta3 = new javax.swing.JTextField();
        varDtLuta4 = new javax.swing.JTextField();
        varDtLuta5 = new javax.swing.JTextField();
        varDtLuta6 = new javax.swing.JTextField();
        varDtLuta7 = new javax.swing.JTextField();
        varDtLuta8 = new javax.swing.JTextField();
        btSalvarLutas = new javax.swing.JButton();
        abaCampQuartas = new javax.swing.JPanel();
        quartas1 = new javax.swing.JLabel();
        varQuartas1Luta1 = new javax.swing.JTextField();
        varQuartas1Luta2 = new javax.swing.JTextField();
        varQuartas2Luta1 = new javax.swing.JTextField();
        varQuartas2Luta2 = new javax.swing.JTextField();
        varQuartas3Luta1 = new javax.swing.JTextField();
        varQuartas3Luta3 = new javax.swing.JTextField();
        varQuartas4Luta1 = new javax.swing.JTextField();
        varQuartas4Luta4 = new javax.swing.JTextField();
        versus1 = new javax.swing.JLabel();
        versus2 = new javax.swing.JLabel();
        versus3 = new javax.swing.JLabel();
        versus4 = new javax.swing.JLabel();
        versus5 = new javax.swing.JLabel();
        versus6 = new javax.swing.JLabel();
        versus7 = new javax.swing.JLabel();
        varArbitroQuartas = new javax.swing.JLabel();
        varDtQuartas1 = new javax.swing.JTextField();
        varDtQuartas2 = new javax.swing.JTextField();
        varDtQuartas3 = new javax.swing.JTextField();
        varDtQuartas4 = new javax.swing.JTextField();
        btQuartasSalvar = new javax.swing.JButton();
        abaCampSemi = new javax.swing.JPanel();
        varArbitroSemi = new javax.swing.JLabel();
        Semi1 = new javax.swing.JLabel();
        Semi2 = new javax.swing.JLabel();
        varSemi1Luta1 = new javax.swing.JTextField();
        varSemi1Luta2 = new javax.swing.JTextField();
        varDtSemi1 = new javax.swing.JTextField();
        varSemi2Luta1 = new javax.swing.JTextField();
        varSemi2Luta2 = new javax.swing.JTextField();
        versus9 = new javax.swing.JLabel();
        versus10 = new javax.swing.JLabel();
        varDtSemi2 = new javax.swing.JTextField();
        varBtSemiSalvar = new javax.swing.JButton();
        abaCampFinal = new javax.swing.JPanel();
        LogoFinal = new javax.swing.JLabel();
        Final = new javax.swing.JLabel();
        versus11 = new javax.swing.JLabel();
        varFinal1 = new javax.swing.JTextField();
        varFinal2 = new javax.swing.JTextField();
        varArbitroFinal = new javax.swing.JLabel();
        varDtFinal = new javax.swing.JTextField();
        btSalvarFinal = new javax.swing.JButton();
        Final1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        versus12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        varArbitroFinal1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(406, 467));

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 153, 153));

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("LUTAS");

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/me/icones/luta-livre.png"))); // NOI18N

        Id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Id.setText("ID:");
        Id.setToolTipText("DIGITE O ID DO CAMPEONATO");

        btPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/me/icones/icone pesquisar.png"))); // NOI18N
        btPesquisa.setBorder(null);
        btPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaActionPerformed(evt);
            }
        });

        tblAtletas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "País", "Altura", "Peso", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAtletas);
        if (tblAtletas.getColumnModel().getColumnCount() > 0) {
            tblAtletas.getColumnModel().getColumn(0).setResizable(false);
            tblAtletas.getColumnModel().getColumn(0).setPreferredWidth(15);
            tblAtletas.getColumnModel().getColumn(1).setResizable(false);
            tblAtletas.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblAtletas.getColumnModel().getColumn(2).setPreferredWidth(35);
            tblAtletas.getColumnModel().getColumn(3).setPreferredWidth(35);
            tblAtletas.getColumnModel().getColumn(4).setPreferredWidth(25);
            tblAtletas.getColumnModel().getColumn(5).setResizable(false);
        }

        btSortear.setText("Sortear");

        javax.swing.GroupLayout abaCampAtletasLayout = new javax.swing.GroupLayout(abaCampAtletas);
        abaCampAtletas.setLayout(abaCampAtletasLayout);
        abaCampAtletasLayout.setHorizontalGroup(
            abaCampAtletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(abaCampAtletasLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(btSortear)
                .addContainerGap())
        );
        abaCampAtletasLayout.setVerticalGroup(
            abaCampAtletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCampAtletasLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSortear)
                .addContainerGap())
        );

        tblCamp.addTab("Atletas", abaCampAtletas);

        tblArbitros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Nac.", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblArbitros.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblArbitros);
        if (tblArbitros.getColumnModel().getColumnCount() > 0) {
            tblArbitros.getColumnModel().getColumn(0).setResizable(false);
            tblArbitros.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblArbitros.getColumnModel().getColumn(1).setResizable(false);
            tblArbitros.getColumnModel().getColumn(1).setPreferredWidth(250);
            tblArbitros.getColumnModel().getColumn(2).setResizable(false);
            tblArbitros.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblArbitros.getColumnModel().getColumn(3).setResizable(false);
            tblArbitros.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        btArbitros.setText("Sortear");

        javax.swing.GroupLayout abaCampArbitrosLayout = new javax.swing.GroupLayout(abaCampArbitros);
        abaCampArbitros.setLayout(abaCampArbitrosLayout);
        abaCampArbitrosLayout.setHorizontalGroup(
            abaCampArbitrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
            .addGroup(abaCampArbitrosLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(btArbitros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abaCampArbitrosLayout.setVerticalGroup(
            abaCampArbitrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCampArbitrosLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btArbitros)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        tblCamp.addTab("Arbitros", abaCampArbitros);

        luta1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        luta1.setText("Luta 1:");

        luta2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        luta2.setText("Luta 2:");

        luta3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        luta3.setText("Luta 3:");

        luta4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        luta4.setText("Luta 4:");

        luta5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        luta5.setText("Luta 5:");

        luta6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        luta6.setText("Luta 6:");

        luta7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        luta7.setText("Luta 7:");

        luta8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        luta8.setText("Luta 8:");

        var1Luta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var1Luta2ActionPerformed(evt);
            }
        });

        var2Luta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var2Luta7ActionPerformed(evt);
            }
        });

        vesus1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vesus1.setText("X");

        vesus2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vesus2.setText("X");

        vesus3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vesus3.setText("X");

        vesus4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vesus4.setText("X");

        vesus5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vesus5.setText("X");

        vesus6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vesus6.setText("X");

        vesus7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vesus7.setText("X");

        vesus8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vesus8.setText("X");

        Arbitro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Arbitro.setText("Arbitro");

        btSalvarLutas.setText("Vencedores");

        javax.swing.GroupLayout abaCampLutasLayout = new javax.swing.GroupLayout(abaCampLutas);
        abaCampLutas.setLayout(abaCampLutasLayout);
        abaCampLutasLayout.setHorizontalGroup(
            abaCampLutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCampLutasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaCampLutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaCampLutasLayout.createSequentialGroup()
                        .addGroup(abaCampLutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(abaCampLutasLayout.createSequentialGroup()
                                .addComponent(luta8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(var1Luta8))
                            .addGroup(abaCampLutasLayout.createSequentialGroup()
                                .addComponent(luta7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(var1Luta7))
                            .addGroup(abaCampLutasLayout.createSequentialGroup()
                                .addComponent(luta6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(var1Luta6))
                            .addGroup(abaCampLutasLayout.createSequentialGroup()
                                .addComponent(luta5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(var1Luta5))
                            .addGroup(abaCampLutasLayout.createSequentialGroup()
                                .addComponent(luta4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(var1Luta4))
                            .addGroup(abaCampLutasLayout.createSequentialGroup()
                                .addComponent(luta3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(var1Luta3))
                            .addGroup(abaCampLutasLayout.createSequentialGroup()
                                .addComponent(luta2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(var1Luta2))
                            .addGroup(abaCampLutasLayout.createSequentialGroup()
                                .addComponent(luta1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(var1Luta1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(abaCampLutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaCampLutasLayout.createSequentialGroup()
                                .addGroup(abaCampLutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vesus2)
                                    .addComponent(vesus1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(abaCampLutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(abaCampLutasLayout.createSequentialGroup()
                                        .addComponent(var2Luta1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(varDtLuta1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                                    .addGroup(abaCampLutasLayout.createSequentialGroup()
                                        .addComponent(var2Luta2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(varDtLuta2))))
                            .addGroup(abaCampLutasLayout.createSequentialGroup()
                                .addGroup(abaCampLutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(abaCampLutasLayout.createSequentialGroup()
                                        .addComponent(vesus4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(var2Luta4))
                                    .addGroup(abaCampLutasLayout.createSequentialGroup()
                                        .addComponent(vesus5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(var2Luta5))
                                    .addGroup(abaCampLutasLayout.createSequentialGroup()
                                        .addComponent(vesus7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(var2Luta7))
                                    .addGroup(abaCampLutasLayout.createSequentialGroup()
                                        .addComponent(vesus8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(var2Luta8))
                                    .addGroup(abaCampLutasLayout.createSequentialGroup()
                                        .addComponent(vesus3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(var2Luta3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(abaCampLutasLayout.createSequentialGroup()
                                        .addComponent(vesus6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(var2Luta6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(abaCampLutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(varDtLuta3)
                                    .addComponent(varDtLuta4)
                                    .addComponent(varDtLuta5)
                                    .addComponent(varDtLuta6)
                                    .addComponent(varDtLuta7)
                                    .addComponent(varDtLuta8))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaCampLutasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Arbitro)
                        .addGap(39, 39, 39))))
            .addGroup(abaCampLutasLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(btSalvarLutas)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        abaCampLutasLayout.setVerticalGroup(
            abaCampLutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCampLutasLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(Arbitro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaCampLutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luta1)
                    .addComponent(var1Luta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vesus1)
                    .addComponent(var2Luta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varDtLuta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaCampLutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luta2)
                    .addComponent(var1Luta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vesus2)
                    .addComponent(var2Luta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varDtLuta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaCampLutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luta3)
                    .addComponent(var1Luta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vesus3)
                    .addComponent(var2Luta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varDtLuta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaCampLutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luta4)
                    .addComponent(var1Luta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vesus4)
                    .addComponent(var2Luta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varDtLuta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaCampLutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luta5)
                    .addComponent(var1Luta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vesus5)
                    .addComponent(var2Luta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varDtLuta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaCampLutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luta6)
                    .addComponent(var1Luta6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vesus6)
                    .addComponent(var2Luta6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varDtLuta6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaCampLutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luta7)
                    .addComponent(var1Luta7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vesus7)
                    .addComponent(var2Luta7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varDtLuta7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaCampLutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luta8)
                    .addComponent(var1Luta8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vesus8)
                    .addComponent(var2Luta8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varDtLuta8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btSalvarLutas)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        tblCamp.addTab("Lutas", abaCampLutas);

        quartas1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quartas1.setText("Quartas 1:");

        versus1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        versus1.setText("X");

        versus2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        versus2.setText("X");

        versus3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        versus3.setText("X");

        versus4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        versus4.setText("X");

        versus5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        versus5.setText("Quartas 2:");

        versus6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        versus6.setText("Quartas 3:");

        versus7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        versus7.setText("Quartas 4:");

        varArbitroQuartas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        varArbitroQuartas.setText("Arbitro");

        btQuartasSalvar.setText("Vencedores");

        javax.swing.GroupLayout abaCampQuartasLayout = new javax.swing.GroupLayout(abaCampQuartas);
        abaCampQuartas.setLayout(abaCampQuartasLayout);
        abaCampQuartasLayout.setHorizontalGroup(
            abaCampQuartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCampQuartasLayout.createSequentialGroup()
                .addGroup(abaCampQuartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quartas1)
                    .addComponent(versus5)
                    .addComponent(versus6)
                    .addComponent(versus7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaCampQuartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(abaCampQuartasLayout.createSequentialGroup()
                        .addComponent(varQuartas4Luta1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(versus4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varQuartas4Luta4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaCampQuartasLayout.createSequentialGroup()
                        .addComponent(varQuartas3Luta1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(versus3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varQuartas3Luta3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaCampQuartasLayout.createSequentialGroup()
                        .addComponent(varQuartas2Luta1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(versus2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varQuartas2Luta2))
                    .addGroup(abaCampQuartasLayout.createSequentialGroup()
                        .addComponent(varQuartas1Luta1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(versus1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varQuartas1Luta2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaCampQuartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(varDtQuartas1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(varDtQuartas2)
                    .addComponent(varDtQuartas3)
                    .addComponent(varDtQuartas4))
                .addContainerGap())
            .addGroup(abaCampQuartasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(varArbitroQuartas)
                .addGap(27, 27, 27))
            .addGroup(abaCampQuartasLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(btQuartasSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abaCampQuartasLayout.setVerticalGroup(
            abaCampQuartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCampQuartasLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(varArbitroQuartas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaCampQuartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quartas1)
                    .addComponent(varQuartas1Luta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(versus1)
                    .addComponent(varQuartas1Luta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varDtQuartas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(abaCampQuartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varQuartas2Luta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(versus2)
                    .addComponent(versus5)
                    .addComponent(varQuartas2Luta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varDtQuartas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(abaCampQuartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varQuartas3Luta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(versus3)
                    .addComponent(versus6)
                    .addComponent(varQuartas3Luta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varDtQuartas3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(abaCampQuartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varQuartas4Luta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(versus4)
                    .addComponent(versus7)
                    .addComponent(varQuartas4Luta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varDtQuartas4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btQuartasSalvar)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        tblCamp.addTab("Quartas de final", abaCampQuartas);

        abaCampSemi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        varArbitroSemi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        varArbitroSemi.setText("Arbitro");
        abaCampSemi.add(varArbitroSemi, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        Semi1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Semi1.setText("Semi 1:");
        abaCampSemi.add(Semi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 48, -1, -1));

        Semi2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Semi2.setText("Semi 2:");
        abaCampSemi.add(Semi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));
        abaCampSemi.add(varSemi1Luta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 149, -1));
        abaCampSemi.add(varSemi1Luta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 149, -1));
        abaCampSemi.add(varDtSemi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 100, -1));
        abaCampSemi.add(varSemi2Luta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 149, -1));
        abaCampSemi.add(varSemi2Luta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 149, -1));

        versus9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        versus9.setText("X");
        abaCampSemi.add(versus9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        versus10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        versus10.setText("X");
        abaCampSemi.add(versus10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));
        abaCampSemi.add(varDtSemi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 200, 100, -1));

        varBtSemiSalvar.setText("Vencedores");
        abaCampSemi.add(varBtSemiSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 298, -1, -1));

        tblCamp.addTab("Semi final", abaCampSemi);

        LogoFinal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/me/icones/icons8-champion-belt-64.png"))); // NOI18N

        Final.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Final.setText("FINAL:");

        versus11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        versus11.setText("x");

        varFinal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varFinal1ActionPerformed(evt);
            }
        });

        varArbitroFinal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        varArbitroFinal.setText("Arbitro:");

        btSalvarFinal.setText("Salvar");

        Final1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Final1.setText("TERCEIRO LUGAR");

        versus12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        versus12.setText("x");

        varArbitroFinal1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        varArbitroFinal1.setText("Arbitro:");

        javax.swing.GroupLayout abaCampFinalLayout = new javax.swing.GroupLayout(abaCampFinal);
        abaCampFinal.setLayout(abaCampFinalLayout);
        abaCampFinalLayout.setHorizontalGroup(
            abaCampFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCampFinalLayout.createSequentialGroup()
                .addGroup(abaCampFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaCampFinalLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(abaCampFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(abaCampFinalLayout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(versus12)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(abaCampFinalLayout.createSequentialGroup()
                                .addComponent(varFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(versus11)
                                .addGap(22, 22, 22)
                                .addComponent(varFinal2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(abaCampFinalLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btSalvarFinal))
                    .addGroup(abaCampFinalLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(abaCampFinalLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(varArbitroFinal))
                    .addGroup(abaCampFinalLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(varArbitroFinal1))
                    .addGroup(abaCampFinalLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addGroup(abaCampFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LogoFinal)
                            .addGroup(abaCampFinalLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Final))))
                    .addGroup(abaCampFinalLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(abaCampFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Final1)
                            .addComponent(varDtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        abaCampFinalLayout.setVerticalGroup(
            abaCampFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCampFinalLayout.createSequentialGroup()
                .addComponent(LogoFinal)
                .addGap(5, 5, 5)
                .addComponent(Final)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaCampFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varFinal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(versus11))
                .addGap(23, 23, 23)
                .addComponent(varArbitroFinal1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(varDtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Final1)
                .addGap(14, 14, 14)
                .addGroup(abaCampFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(versus12))
                .addGap(19, 19, 19)
                .addComponent(varArbitroFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSalvarFinal)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        tblCamp.addTab("Final", abaCampFinal);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(Titulo))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(Id)
                .addGap(4, 4, 4)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(LOGO))
                    .addComponent(varIDpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(tblCamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(Titulo)
                .addGap(6, 6, 6)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(Id))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(LOGO)
                        .addGap(6, 6, 6)
                        .addComponent(varIDpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(tblCamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 510, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void var2Luta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var2Luta7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_var2Luta7ActionPerformed

    private void varFinal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varFinal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varFinal1ActionPerformed

    private void var1Luta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var1Luta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_var1Luta2ActionPerformed

    private void btPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaActionPerformed
        pesquisandoArbitroCampeonato();
        pesquisandoAtletaCampeonato();
    }//GEN-LAST:event_btPesquisaActionPerformed
    public void pesquisandoArbitroCampeonato() {
        ArbitroDao arbitroDao = new ArbitroDao();
        ResultSet resultadopesquisa = arbitroDao.pesquisarArbitro();
        tblArbitros.setModel(DbUtils.resultSetToTableModel(resultadopesquisa));
    }

    public void pesquisandoAtletaCampeonato() {
        int id = Integer.parseInt(varIDpesquisa.getText().trim());

        LutaDao lutadao = new LutaDao();
        ResultSet atletasPesquisados = lutadao.atletasCampeonato(id);
//        tblAtletas.setModel(DbUtils.resultSetToTableModel(atletasPesquisados));
        List<Atleta> atletas = new ArrayList<>();
        DefaultTableModel modelo = (DefaultTableModel) tblAtletas.getModel();
        try {
            while (atletasPesquisados.next()) {
                Atleta atleta = new Atleta();

                atleta.setId(atletasPesquisados.getInt("idatleta"));
                atleta.setNome(atletasPesquisados.getString("nome"));
                atleta.setNacionalidade(atletasPesquisados.getString("nacionalidade"));
                atleta.setPeso(Double.parseDouble(atletasPesquisados.getString("peso")));
                atleta.setAltura(Double.parseDouble(atletasPesquisados.getString("altura")));
                atleta.setCategoria(atletasPesquisados.getString("categoria"));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Lutas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Arbitro;
    private javax.swing.JLabel Final;
    private javax.swing.JLabel Final1;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel LOGO;
    private javax.swing.JLabel LogoFinal;
    private javax.swing.JLabel Semi1;
    private javax.swing.JLabel Semi2;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel abaCampArbitros;
    private javax.swing.JPanel abaCampAtletas;
    private javax.swing.JPanel abaCampFinal;
    private javax.swing.JPanel abaCampLutas;
    private javax.swing.JPanel abaCampQuartas;
    private javax.swing.JPanel abaCampSemi;
    private javax.swing.JButton btArbitros;
    private javax.swing.JButton btPesquisa;
    private javax.swing.JButton btQuartasSalvar;
    private javax.swing.JButton btSalvarFinal;
    private javax.swing.JButton btSalvarLutas;
    private javax.swing.JButton btSortear;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel luta1;
    private javax.swing.JLabel luta2;
    private javax.swing.JLabel luta3;
    private javax.swing.JLabel luta4;
    private javax.swing.JLabel luta5;
    private javax.swing.JLabel luta6;
    private javax.swing.JLabel luta7;
    private javax.swing.JLabel luta8;
    private javax.swing.JLabel quartas1;
    private javax.swing.JTable tblArbitros;
    private javax.swing.JTable tblAtletas;
    private javax.swing.JTabbedPane tblCamp;
    private javax.swing.JTextField var1Luta1;
    private javax.swing.JTextField var1Luta2;
    private javax.swing.JTextField var1Luta3;
    private javax.swing.JTextField var1Luta4;
    private javax.swing.JTextField var1Luta5;
    private javax.swing.JTextField var1Luta6;
    private javax.swing.JTextField var1Luta7;
    private javax.swing.JTextField var1Luta8;
    private javax.swing.JTextField var2Luta1;
    private javax.swing.JTextField var2Luta2;
    private javax.swing.JTextField var2Luta3;
    private javax.swing.JTextField var2Luta4;
    private javax.swing.JTextField var2Luta5;
    private javax.swing.JTextField var2Luta6;
    private javax.swing.JTextField var2Luta7;
    private javax.swing.JTextField var2Luta8;
    private javax.swing.JLabel varArbitroFinal;
    private javax.swing.JLabel varArbitroFinal1;
    private javax.swing.JLabel varArbitroQuartas;
    private javax.swing.JLabel varArbitroSemi;
    private javax.swing.JButton varBtSemiSalvar;
    private javax.swing.JTextField varDtFinal;
    private javax.swing.JTextField varDtLuta1;
    private javax.swing.JTextField varDtLuta2;
    private javax.swing.JTextField varDtLuta3;
    private javax.swing.JTextField varDtLuta4;
    private javax.swing.JTextField varDtLuta5;
    private javax.swing.JTextField varDtLuta6;
    private javax.swing.JTextField varDtLuta7;
    private javax.swing.JTextField varDtLuta8;
    private javax.swing.JTextField varDtQuartas1;
    private javax.swing.JTextField varDtQuartas2;
    private javax.swing.JTextField varDtQuartas3;
    private javax.swing.JTextField varDtQuartas4;
    private javax.swing.JTextField varDtSemi1;
    private javax.swing.JTextField varDtSemi2;
    private javax.swing.JTextField varFinal1;
    private javax.swing.JTextField varFinal2;
    private javax.swing.JTextField varIDpesquisa;
    private javax.swing.JTextField varQuartas1Luta1;
    private javax.swing.JTextField varQuartas1Luta2;
    private javax.swing.JTextField varQuartas2Luta1;
    private javax.swing.JTextField varQuartas2Luta2;
    private javax.swing.JTextField varQuartas3Luta1;
    private javax.swing.JTextField varQuartas3Luta3;
    private javax.swing.JTextField varQuartas4Luta1;
    private javax.swing.JTextField varQuartas4Luta4;
    private javax.swing.JTextField varSemi1Luta1;
    private javax.swing.JTextField varSemi1Luta2;
    private javax.swing.JTextField varSemi2Luta1;
    private javax.swing.JTextField varSemi2Luta2;
    private javax.swing.JLabel versus1;
    private javax.swing.JLabel versus10;
    private javax.swing.JLabel versus11;
    private javax.swing.JLabel versus12;
    private javax.swing.JLabel versus2;
    private javax.swing.JLabel versus3;
    private javax.swing.JLabel versus4;
    private javax.swing.JLabel versus5;
    private javax.swing.JLabel versus6;
    private javax.swing.JLabel versus7;
    private javax.swing.JLabel versus9;
    private javax.swing.JLabel vesus1;
    private javax.swing.JLabel vesus2;
    private javax.swing.JLabel vesus3;
    private javax.swing.JLabel vesus4;
    private javax.swing.JLabel vesus5;
    private javax.swing.JLabel vesus6;
    private javax.swing.JLabel vesus7;
    private javax.swing.JLabel vesus8;
    // End of variables declaration//GEN-END:variables
}
