/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.me.telas;

import br.com.me.DAO.ArbitroDao;
import br.com.me.entidade.Arbitro;

/**
 *
 * @author marcelo jr
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel2 = new keeptoo.KGradientPanel();
        varDesktop = new javax.swing.JDesktopPane();
        varLogo = new javax.swing.JLabel();
        varBoasVindas = new javax.swing.JLabel();
        varData = new javax.swing.JLabel();
        varHora = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JMenuBar();
        MenuCamp = new javax.swing.JMenu();
        MenuCampCriar = new javax.swing.JMenuItem();
        MenuCampLutas = new javax.swing.JMenuItem();
        MenuCadastro = new javax.swing.JMenu();
        MenuCadastroLutador = new javax.swing.JMenuItem();
        MenuCadastroArbitro = new javax.swing.JMenuItem();
        ManuCadastroAtlCamp = new javax.swing.JRadioButtonMenuItem();
        MenuHist = new javax.swing.JMenu();
        MenuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerador de campeonato v2021");
        setResizable(false);

        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        varDesktop.setPreferredSize(new java.awt.Dimension(512, 564));

        javax.swing.GroupLayout varDesktopLayout = new javax.swing.GroupLayout(varDesktop);
        varDesktop.setLayout(varDesktopLayout);
        varDesktopLayout.setHorizontalGroup(
            varDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        varDesktopLayout.setVerticalGroup(
            varDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        kGradientPanel2.add(varDesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 630));

        varLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/me/icones/logo integrador.png"))); // NOI18N
        kGradientPanel2.add(varLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        varBoasVindas.setText("Bem vindo, Nome");
        kGradientPanel2.add(varBoasVindas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 92, -1));

        varData.setText("Data");
        kGradientPanel2.add(varData, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));

        varHora.setText("Hora");
        kGradientPanel2.add(varHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, -1, -1));

        MenuCamp.setText("Campeonato");

        MenuCampCriar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        MenuCampCriar.setText("Criar");
        MenuCampCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCampCriarActionPerformed(evt);
            }
        });
        MenuCamp.add(MenuCampCriar);

        MenuCampLutas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        MenuCampLutas.setText("Lutas");
        MenuCampLutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCampLutasActionPerformed(evt);
            }
        });
        MenuCamp.add(MenuCampLutas);

        MenuPrincipal.add(MenuCamp);

        MenuCadastro.setText("Cadastro");

        MenuCadastroLutador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        MenuCadastroLutador.setText("Lutador");
        MenuCadastroLutador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroLutadorActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadastroLutador);

        MenuCadastroArbitro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        MenuCadastroArbitro.setText("Arbitro");
        MenuCadastroArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroArbitroActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadastroArbitro);

        ManuCadastroAtlCamp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        ManuCadastroAtlCamp.setSelected(true);
        ManuCadastroAtlCamp.setText("AtletaCampeonato");
        ManuCadastroAtlCamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManuCadastroAtlCampActionPerformed(evt);
            }
        });
        MenuCadastro.add(ManuCadastroAtlCamp);

        MenuPrincipal.add(MenuCadastro);

        MenuHist.setText("Histórico");
        MenuPrincipal.add(MenuHist);

        MenuAjuda.setText("Ajuda");
        MenuPrincipal.add(MenuAjuda);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCadastroLutadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroLutadorActionPerformed
            CadastroLutador cadastroLutador = new CadastroLutador();
            cadastroLutador.setVisible(true);
            varDesktop.add(cadastroLutador);
    }//GEN-LAST:event_MenuCadastroLutadorActionPerformed

    private void MenuCampCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCampCriarActionPerformed
       CriarCampeonato campeonato = new CriarCampeonato();
       campeonato.setVisible(true);
       varDesktop.add(campeonato);
    }//GEN-LAST:event_MenuCampCriarActionPerformed

    private void MenuCampLutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCampLutasActionPerformed
        Lutas lutas = new Lutas();
        lutas.setVisible(true);
        varDesktop.add(lutas);
    }//GEN-LAST:event_MenuCampLutasActionPerformed

    private void MenuCadastroArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroArbitroActionPerformed
      CadastroArbitro arbitro = new CadastroArbitro();
      arbitro.setVisible(true);
      varDesktop.add(arbitro);
              
    }//GEN-LAST:event_MenuCadastroArbitroActionPerformed

    private void ManuCadastroAtlCampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManuCadastroAtlCampActionPerformed
       AtletaCampeonato atletaCampeonato = new AtletaCampeonato();
       atletaCampeonato.setVisible(true);
       varDesktop.add(atletaCampeonato);
    }//GEN-LAST:event_ManuCadastroAtlCampActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem ManuCadastroAtlCamp;
    private javax.swing.JMenu MenuAjuda;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenuItem MenuCadastroArbitro;
    private javax.swing.JMenuItem MenuCadastroLutador;
    private javax.swing.JMenu MenuCamp;
    private javax.swing.JMenuItem MenuCampCriar;
    private javax.swing.JMenuItem MenuCampLutas;
    private javax.swing.JMenu MenuHist;
    private javax.swing.JMenuBar MenuPrincipal;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel varBoasVindas;
    private javax.swing.JLabel varData;
    private javax.swing.JDesktopPane varDesktop;
    private javax.swing.JLabel varHora;
    private javax.swing.JLabel varLogo;
    // End of variables declaration//GEN-END:variables
}
