/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.me.telas;

import br.com.me.DAO.ArbitroDao;
import br.com.me.entidade.Arbitro;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author marcelo jr
 */
public class TelaPrincipal extends javax.swing.JFrame implements Runnable {

    String hora, minuto, segundo;
    Thread hilo;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        hilo = new Thread(this);
        hilo.start();
        setVisible(true);
    }

    private void hora() {
        Date data = new Date();
        SimpleDateFormat formatado = new SimpleDateFormat("hh:mm:ss");
        varHora.setText(formatado.format(data));
    }

    private void data() {
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.DEFAULT);
        System.out.println(formatador);
        varData.setText(formatador.format(data));
    }

    public void hora2() {
        Calendar calendario = new GregorianCalendar();
        Date horaatual = new Date();
        calendario.setTime(horaatual);
        hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        minuto = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundo = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);
    }

    public void run() {
        Thread current = Thread.currentThread();

        while (current == hilo) {
            hora2();
            varHora.setText(hora + ":" + minuto + ":" + segundo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel2 = new keeptoo.KGradientPanel();
        varDesktop = new javax.swing.JDesktopPane();
        varLogo = new javax.swing.JLabel();
        varData = new javax.swing.JLabel();
        varHora = new javax.swing.JLabel();
        varUsuario = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JMenuBar();
        MenuCamp = new javax.swing.JMenu();
        MenuCampCriar = new javax.swing.JMenuItem();
        MenuCampLutas = new javax.swing.JMenuItem();
        MenuCadastro = new javax.swing.JMenu();
        MenuCadastroLutador = new javax.swing.JMenuItem();
        MenuCadastroArbitro = new javax.swing.JMenuItem();
        MenuHist = new javax.swing.JMenu();
        MenuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerador de campeonato v2021");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        varDesktop.setPreferredSize(new java.awt.Dimension(512, 564));

        javax.swing.GroupLayout varDesktopLayout = new javax.swing.GroupLayout(varDesktop);
        varDesktop.setLayout(varDesktopLayout);
        varDesktopLayout.setHorizontalGroup(
            varDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        varDesktopLayout.setVerticalGroup(
            varDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        kGradientPanel2.add(varDesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 630));

        varLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/me/icones/logo integrador.png"))); // NOI18N
        kGradientPanel2.add(varLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        varData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varData.setForeground(new java.awt.Color(255, 255, 255));
        varData.setText("Data");
        kGradientPanel2.add(varData, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));

        varHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varHora.setForeground(new java.awt.Color(255, 255, 255));
        varHora.setText("Hora");
        kGradientPanel2.add(varHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, -1, -1));

        varUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        varUsuario.setForeground(new java.awt.Color(255, 255, 255));
        varUsuario.setText("usuario");
        kGradientPanel2.add(varUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        MenuCamp.setText("Campeonato");

        MenuCampCriar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        MenuCampCriar.setText("Criar");
        MenuCampCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCampCriarActionPerformed(evt);
            }
        });
        MenuCamp.add(MenuCampCriar);

        MenuCampLutas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        MenuCampLutas.setText("Lutas");
        MenuCampLutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCampLutasActionPerformed(evt);
            }
        });
        MenuCamp.add(MenuCampLutas);

        MenuPrincipal.add(MenuCamp);

        MenuCadastro.setText("Cadastro");

        MenuCadastroLutador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        MenuCadastroLutador.setText("Lutador");
        MenuCadastroLutador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroLutadorActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadastroLutador);

        MenuCadastroArbitro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        MenuCadastroArbitro.setText("Arbitro");
        MenuCadastroArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroArbitroActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadastroArbitro);

        MenuPrincipal.add(MenuCadastro);

        MenuHist.setText("Histórico");
        MenuPrincipal.add(MenuHist);

        MenuAjuda.setText("Ajuda");
        MenuPrincipal.add(MenuAjuda);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(794, 697));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCadastroLutadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroLutadorActionPerformed
        CadastroLutador cadastroLutador = new CadastroLutador();
        cadastroLutador.setVisible(true);
        varDesktop.add(cadastroLutador);
    }//GEN-LAST:event_MenuCadastroLutadorActionPerformed

    private void MenuCampCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCampCriarActionPerformed
        CriarCampeonato campeonato = new CriarCampeonato();
        campeonato.setVisible(true);
        varDesktop.add(campeonato);
    }//GEN-LAST:event_MenuCampCriarActionPerformed

    private void MenuCampLutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCampLutasActionPerformed
        Lutas lutas = new Lutas();
        lutas.setVisible(true);
        varDesktop.add(lutas);
    }//GEN-LAST:event_MenuCampLutasActionPerformed

    private void MenuCadastroArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroArbitroActionPerformed
        CadastroArbitro arbitro = new CadastroArbitro();
        arbitro.setVisible(true);
        varDesktop.add(arbitro);

    }//GEN-LAST:event_MenuCadastroArbitroActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       data();
       run();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAjuda;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenuItem MenuCadastroArbitro;
    private javax.swing.JMenuItem MenuCadastroLutador;
    private javax.swing.JMenu MenuCamp;
    private javax.swing.JMenuItem MenuCampCriar;
    private javax.swing.JMenuItem MenuCampLutas;
    private javax.swing.JMenu MenuHist;
    private javax.swing.JMenuBar MenuPrincipal;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel varData;
    private javax.swing.JDesktopPane varDesktop;
    private javax.swing.JLabel varHora;
    private javax.swing.JLabel varLogo;
    public static javax.swing.JLabel varUsuario;
    // End of variables declaration//GEN-END:variables
}
